# Generated by Django 4.2.17 on 2024-12-12 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='currency_from',
            field=models.CharField(choices=[('USD', 'Dólar Estadounidense'), ('USDT', 'Precio USDT')], max_length=4),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='currency_to',
            field=models.CharField(choices=[('USD', 'Dólar Estadounidense'), ('USDT', 'Precio USDT')], max_length=4),
        ),
    ]
