# Generated by Django 4.2.17 on 2024-12-13 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_alter_exchangerate_currency_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='currency_from',
            field=models.CharField(choices=[('USD', 'Dólar Estadounidense'), ('USDT', 'USDT'), ('PEN', 'Nuevo Sol Peruano')], max_length=4),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='currency_to',
            field=models.CharField(choices=[('USD', 'Dólar Estadounidense'), ('USDT', 'USDT'), ('PEN', 'Nuevo Sol Peruano')], max_length=4),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='rate',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
